cc_binary(
  name = "control",
  srcs = ["main.cc"],
  deps = [
    "//apollo/core:conveyor_controller",
    "//apollo/core:digger_controller",
    "//apollo/core:safe_exit",
    "//apollo/core:wheel_controller",
    "//apollo/remote:connection_manager",
    "//apollo/remote:network_packet",
  ],
)
